// generated file. template : widgetfactorylookup.vm

package emforium.gwt.widget.gxt;

import emforium.gwt.widget.GwtObjectFactoryRegistry;
import emforium.gwt.widget.GwtObjectFactory;
import java.util.Map;

public class GwtFactoryRegistryImpl implements GwtObjectFactoryRegistry {
    
    public void registerFactories(String prefix,Map<String, GwtObjectFactory<?>> types) {
        // register generated widgets
        types.put(prefix+ToolTipFactory.XML_TAG, new ToolTipFactory());
        types.put(prefix+PortletFactory.XML_TAG, new PortletFactory());
        types.put(prefix+ToggleToolItemFactory.XML_TAG, new ToggleToolItemFactory());
        types.put(prefix+InsertFactory.XML_TAG, new InsertFactory());
        types.put(prefix+CollapsePanelFactory.XML_TAG, new CollapsePanelFactory());
        types.put(prefix+ToolItemFactory.XML_TAG, new ToolItemFactory());
        types.put(prefix+TwinTriggerFieldFactory.XML_TAG, new TwinTriggerFieldFactory());
        types.put(prefix+TreeTableFactory.XML_TAG, new TreeTableFactory());
        types.put(prefix+CheckBoxGroupFactory.XML_TAG, new CheckBoxGroupFactory());
        types.put(prefix+StatusProxyFactory.XML_TAG, new StatusProxyFactory());
        types.put(prefix+FormPanelFactory.XML_TAG, new FormPanelFactory());
        types.put(prefix+ProgressBarFactory.XML_TAG, new ProgressBarFactory());
        types.put(prefix+QuickTipFactory.XML_TAG, new QuickTipFactory());
        types.put(prefix+RadioGroupFactory.XML_TAG, new RadioGroupFactory());
        types.put(prefix+FillButtonFactory.XML_TAG, new FillButtonFactory());
        types.put(prefix+EditorFactory.XML_TAG, new EditorFactory());
        types.put(prefix+AdapterMenuItemFactory.XML_TAG, new AdapterMenuItemFactory());
        types.put(prefix+CenterLayoutFactory.XML_TAG, new CenterLayoutFactory());
        types.put(prefix+FillToolItemFactory.XML_TAG, new FillToolItemFactory());
        types.put(prefix+AccordionLayoutFactory.XML_TAG, new AccordionLayoutFactory());
        types.put(prefix+ButtonAdapterFactory.XML_TAG, new ButtonAdapterFactory());
        types.put(prefix+LabelToolItemFactory.XML_TAG, new LabelToolItemFactory());
        types.put(prefix+TableRowLayoutFactory.XML_TAG, new TableRowLayoutFactory());
        types.put(prefix+TableFactory.XML_TAG, new TableFactory());
        types.put(prefix+ToolButtonFactory.XML_TAG, new ToolButtonFactory());
        types.put(prefix+FileUploadFieldFactory.XML_TAG, new FileUploadFieldFactory());
        types.put(prefix+ListViewFactory.XML_TAG, new ListViewFactory());
        types.put(prefix+HtmlContainerFactory.XML_TAG, new HtmlContainerFactory());
        types.put(prefix+BorderLayoutFactory.XML_TAG, new BorderLayoutFactory());
        types.put(prefix+TableLayoutFactory.XML_TAG, new TableLayoutFactory());
        types.put(prefix+TreeTableItemFactory.XML_TAG, new TreeTableItemFactory());
        types.put(prefix+DateMenuFactory.XML_TAG, new DateMenuFactory());
        types.put(prefix+ButtonBarFactory.XML_TAG, new ButtonBarFactory());
        types.put(prefix+TextFieldFactory.XML_TAG, new TextFieldFactory());
        types.put(prefix+TreeFactory.XML_TAG, new TreeFactory());
        types.put(prefix+SplitBarFactory.XML_TAG, new SplitBarFactory());
        types.put(prefix+RowLayoutFactory.XML_TAG, new RowLayoutFactory());
        types.put(prefix+PngImageFactory.XML_TAG, new PngImageFactory());
        types.put(prefix+RootTreeTableItemFactory.XML_TAG, new RootTreeTableItemFactory());
        types.put(prefix+CardLayoutFactory.XML_TAG, new CardLayoutFactory());
        types.put(prefix+ColumnLayoutFactory.XML_TAG, new ColumnLayoutFactory());
        types.put(prefix+DataListFactory.XML_TAG, new DataListFactory());
        types.put(prefix+ToolBarFactory.XML_TAG, new ToolBarFactory());
        types.put(prefix+ThemeSelectorFactory.XML_TAG, new ThemeSelectorFactory());
        types.put(prefix+MultiFieldFactory.XML_TAG, new MultiFieldFactory());
        types.put(prefix+CheckBoxFactory.XML_TAG, new CheckBoxFactory());
        types.put(prefix+ShadowFactory.XML_TAG, new ShadowFactory());
        types.put(prefix+AdapterToolItemFactory.XML_TAG, new AdapterToolItemFactory());
        types.put(prefix+HtmlFactory.XML_TAG, new HtmlFactory());
        types.put(prefix+DatePickerFactory.XML_TAG, new DatePickerFactory());
        types.put(prefix+SeparatorMenuItemFactory.XML_TAG, new SeparatorMenuItemFactory());
        types.put(prefix+ComponentCompositeFactory.XML_TAG, new ComponentCompositeFactory());
        types.put(prefix+CheckMenuItemFactory.XML_TAG, new CheckMenuItemFactory());
        types.put(prefix+PortalFactory.XML_TAG, new PortalFactory());
        types.put(prefix+IconButtonFactory.XML_TAG, new IconButtonFactory());
        types.put(prefix+BoxComponentFactory.XML_TAG, new BoxComponentFactory());
        types.put(prefix+StatusBarFactory.XML_TAG, new StatusBarFactory());
        types.put(prefix+HorizontalPanelFactory.XML_TAG, new HorizontalPanelFactory());
        types.put(prefix+HeaderFactory.XML_TAG, new HeaderFactory());
        types.put(prefix+TreeTableHeaderFactory.XML_TAG, new TreeTableHeaderFactory());
        types.put(prefix+TabPanelFactory.XML_TAG, new TabPanelFactory());
        types.put(prefix+TableColumnUIFactory.XML_TAG, new TableColumnUIFactory());
        types.put(prefix+GridFactory.XML_TAG, new GridFactory());
        types.put(prefix+FitLayoutFactory.XML_TAG, new FitLayoutFactory());
        types.put(prefix+DocumentFactory.XML_TAG, new DocumentFactory());
        types.put(prefix+WindowFactory.XML_TAG, new WindowFactory());
        types.put(prefix+SeparatorToolItemFactory.XML_TAG, new SeparatorToolItemFactory());
        types.put(prefix+FlowLayoutFactory.XML_TAG, new FlowLayoutFactory());
        types.put(prefix+ViewportFactory.XML_TAG, new ViewportFactory());
        types.put(prefix+WidgetComponentFactory.XML_TAG, new WidgetComponentFactory());
        types.put(prefix+MenuItemFactory.XML_TAG, new MenuItemFactory());
        types.put(prefix+ContentPanelFactory.XML_TAG, new ContentPanelFactory());
        types.put(prefix+SplitButtonFactory.XML_TAG, new SplitButtonFactory());
        types.put(prefix+ListFieldFactory.XML_TAG, new ListFieldFactory());
        types.put(prefix+ToggleButtonFactory.XML_TAG, new ToggleButtonFactory());
        types.put(prefix+ScrollContainerFactory.XML_TAG, new ScrollContainerFactory());
        types.put(prefix+EditorGridFactory.XML_TAG, new EditorGridFactory());
        types.put(prefix+VerticalPanelFactory.XML_TAG, new VerticalPanelFactory());
        types.put(prefix+FramePanelFactory.XML_TAG, new FramePanelFactory());
        types.put(prefix+StatusButtonBarFactory.XML_TAG, new StatusButtonBarFactory());
        types.put(prefix+PopupFactory.XML_TAG, new PopupFactory());
        types.put(prefix+DateMenuItemFactory.XML_TAG, new DateMenuItemFactory());
        types.put(prefix+MenuFactory.XML_TAG, new MenuFactory());
        types.put(prefix+LabelFieldFactory.XML_TAG, new LabelFieldFactory());
        types.put(prefix+TriggerFieldFactory.XML_TAG, new TriggerFieldFactory());
        types.put(prefix+TabItemFactory.XML_TAG, new TabItemFactory());
        types.put(prefix+DualListFieldFactory.XML_TAG, new DualListFieldFactory());
        types.put(prefix+CellEditorFactory.XML_TAG, new CellEditorFactory());
        types.put(prefix+DataViewItemFactory.XML_TAG, new DataViewItemFactory());
        types.put(prefix+ButtonFactory.XML_TAG, new ButtonFactory());
        types.put(prefix+TextAreaFactory.XML_TAG, new TextAreaFactory());
        types.put(prefix+CompositeFactory.XML_TAG, new CompositeFactory());
        types.put(prefix+DialogFactory.XML_TAG, new DialogFactory());
        types.put(prefix+TableHeaderFactory.XML_TAG, new TableHeaderFactory());
        types.put(prefix+LayoutContainerFactory.XML_TAG, new LayoutContainerFactory());
        types.put(prefix+ModalPanelFactory.XML_TAG, new ModalPanelFactory());
        types.put(prefix+HiddenFieldFactory.XML_TAG, new HiddenFieldFactory());
        types.put(prefix+NumberFieldFactory.XML_TAG, new NumberFieldFactory());
        types.put(prefix+FormLayoutFactory.XML_TAG, new FormLayoutFactory());
        types.put(prefix+FieldSetFactory.XML_TAG, new FieldSetFactory());
        types.put(prefix+TreeItemFactory.XML_TAG, new TreeItemFactory());
        types.put(prefix+InfoFactory.XML_TAG, new InfoFactory());
        types.put(prefix+TableItemFactory.XML_TAG, new TableItemFactory());
        types.put(prefix+DateFieldFactory.XML_TAG, new DateFieldFactory());
        types.put(prefix+AnchorLayoutFactory.XML_TAG, new AnchorLayoutFactory());
        types.put(prefix+TimeFieldFactory.XML_TAG, new TimeFieldFactory());
        types.put(prefix+CardPanelFactory.XML_TAG, new CardPanelFactory());
        types.put(prefix+TextToolItemFactory.XML_TAG, new TextToolItemFactory());
        types.put(prefix+ComboBoxFactory.XML_TAG, new ComboBoxFactory());
        types.put(prefix+RadioFactory.XML_TAG, new RadioFactory());
        types.put(prefix+TipFactory.XML_TAG, new TipFactory());
        types.put(prefix+PagingToolBarFactory.XML_TAG, new PagingToolBarFactory());
        types.put(prefix+TextFactory.XML_TAG, new TextFactory());
        types.put(prefix+DataListItemFactory.XML_TAG, new DataListItemFactory());
        types.put(prefix+AdapterFieldFactory.XML_TAG, new AdapterFieldFactory());
        types.put(prefix+SimpleComboBoxFactory.XML_TAG, new SimpleComboBoxFactory());
        types.put(prefix+FillLayoutFactory.XML_TAG, new FillLayoutFactory());
        types.put(prefix+DataViewFactory.XML_TAG, new DataViewFactory());
        types.put(prefix+AbsoluteLayoutFactory.XML_TAG, new AbsoluteLayoutFactory());
        types.put(prefix+SplitToolItemFactory.XML_TAG, new SplitToolItemFactory());
    }
}
